[package]
name = "mpc-notify"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1

[dependencies]
home = "^0.5"
notify-rust = "^4.5"
mpd = "0.0.12"
